# Generated by Django 5.1.3 on 2024-12-17 22:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_imageuploader_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploader',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='images/'),
        ),
    ]
