# Generated by Django 5.1.3 on 2024-12-23 17:35

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_alter_imageuploader_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='images/')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotator.imageuploader')),
            ],
        ),
    ]
